<a href="https://colab.research.google.com/github/ai7dnn/2026-1-BDA/blob/main/code/numpy_cheat_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 기초 치트시트 강의형 노트북

이 노트북은 첨부된 **NumPy Basics Cheat Sheet**를 바탕으로, 단순 명령어 나열이 아니라 **설명 + 코드 + 예상 결과 해설** 방식으로 다시 구성한 학습용 자료입니다.  
초보자가 순서대로 실행하면서 NumPy의 핵심 개념을 익힐 수 있도록 각 섹션의 마크다운 설명을 자세히 한글로 보강했습니다.

## 학습 목표

- NumPy 배열이 파이썬 리스트와 어떻게 다른지 이해하기
- 배열 생성, 연산, 집계, 인덱싱, 형태 변환을 직접 실행해 보기
- 파일 저장/불러오기와 자료형 확인까지 한 번에 익히기
- 치트시트의 예제를 실제 수업 자료처럼 따라가며 학습하기

## 0. 준비

먼저 NumPy를 불러옵니다. 보통 데이터 과학 코드에서는 `numpy`를 `np`라는 별칭으로 많이 사용합니다.  
또한 출력 옵션을 조금 조정해서 소수점 자릿수와 배열 출력을 보기 좋게 맞추겠습니다.

In [1]:
# NumPy 라이브러리를 불러오고, 배열 출력 형식을 보기 좋게 설정합니다.
import numpy as np
# suppress=True는 과학적 표기법(예: 1.23e-10)을 억제하고
# 항상 고정 소수점 표기법(fixed point notation)을 사용
np.set_printoptions(suppress=True, precision=4)

### 실행 결과 예시

이 셀은 보통 별도의 출력이 없습니다.  
하지만 이후부터 `np.array`, `np.zeros`, `np.arange` 같은 NumPy 기능을 바로 사용할 수 있게 됩니다.

## 1. 기본 배열 만들기

치트시트는 1차원, 2차원, 3차원 배열 예제로 시작합니다. NumPy의 핵심은 **동일한 자료형을 가진 다차원 배열**을 빠르게 다룰 수 있다는 점입니다.  
아래에서는 `a`를 1차원 배열, `b`를 2차원 배열, `c`를 3차원 배열로 만들어 보겠습니다.

In [2]:
# 1차원, 2차원, 3차원 NumPy 배열을 생성하는 예제입니다.
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]], dtype=float)

print('a =\n', a)
print('b =\n', b)
print('c =\n', c)

a =
 [1 2 3]
b =
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
c =
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


### 실행 결과 예시

- `a`는 `[1 2 3]` 형태의 1차원 배열로 출력됩니다.  
- `b`는 2행 3열 구조의 2차원 배열로 보입니다.  
- `c`는 2개의 2차원 배열을 포함한 3차원 배열로 출력됩니다.

이 단계에서 중요한 점은, NumPy 배열은 차원 수가 올라가도 **하나의 일관된 객체**로 다뤄진다는 것입니다.

## 2. 초기화용 배열 만들기

실무에서는 데이터를 바로 입력하기보다, 먼저 원하는 모양의 배열을 만든 뒤 값을 채우는 경우가 많습니다.  
치트시트에는 0으로 채운 배열, 1로 채운 배열, 일정 간격 배열, 균등 분할 배열, 상수 배열, 단위행렬, 난수 배열, 빈 배열이 소개됩니다.

In [4]:
# 0, 1, 등차수열, 균등분할, 상수, 단위행렬, 난수, 빈 배열을 만드는 예제입니다.
zeros_arr = np.zeros((3, 4))
ones_arr = np.ones((2, 3, 4), dtype=np.int16)
print('np.zeros((3,4)) =\n', zeros_arr)
print('np.ones((2,3,4), dtype=np.int16) =\n', ones_arr)

np.zeros((3,4)) =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
np.ones((2,3,4), dtype=np.int16) =
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [6]:
d = np.arange(10, 25, 5)
lin = np.linspace(0, 2, 9) # step: (2-0)/8 = .25

print('np.arange(10,25,5) =', d)
print('np.linspace(0,2,9) =', lin)

np.arange(10,25,5) = [10 15 20]
np.linspace(0,2,9) = [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [7]:
e = np.full((2, 2), 7)
f = np.eye(2)
print('np.full((2,2),7) =\n', e)
print('np.eye(2) =\n', f)

np.full((2,2),7) =
 [[7 7]
 [7 7]]
np.eye(2) =
 [[1. 0.]
 [0. 1.]]


In [9]:
rand_arr = np.random.random((2, 2))
empty_arr = np.empty((3, 2))

print('np.random.random((2,2)) =\n', rand_arr)
print('np.empty((3,2)) =\n', empty_arr)

np.random.random((2,2)) =
 [[0.2924 0.1677]
 [0.4752 0.0254]]
np.empty((3,2)) =
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


최근 사용을 권장하는 난수 생성 방법

In [100]:
rng = np.random.default_rng(1234)
rng.random((2, 2))

array([[0.9767, 0.3802],
       [0.9232, 0.2617]])

In [101]:
rng.standard_normal((3, 2))

array([[ 0.8637,  2.9131],
       [-1.4788,  0.9455],
       [-1.6661,  0.3437]])

In [102]:
rng.integers(0, 10, (3, 3))

array([[5, 4, 2],
       [6, 8, 8],
       [6, 8, 5]])

### 실행 결과 예시

- `np.zeros((3,4))`는 3행 4열의 0 배열을 만듭니다.  
- `np.arange(10,25,5)`는 `[10 15 20]`처럼 일정 간격의 값을 만듭니다.  
- `np.linspace(0,2,9)`는 0부터 2까지를 9개 구간으로 균등하게 나눕니다.  
- `np.eye(2)`는 선형대수에서 자주 쓰는 2x2 단위행렬입니다.  
- `np.random.random((2,2))`의 값은 실행할 때마다 달라집니다.  
- `np.empty((3,2))`는 값을 초기화하지 않기 때문에 내부 값이 예측과 다를 수 있습니다.

## 3. 배열 정보 확인하기

배열을 만들었다면, 그 배열의 구조를 먼저 파악해야 합니다.  
치트시트에는 shape, 길이, 차원 수, 전체 원소 수, 자료형 확인, 자료형 변환 예제가 포함되어 있습니다. [file:1]

In [13]:
a, b, e

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 array([[7, 7],
        [7, 7]]))

In [14]:
# 배열의 크기, 차원 수, 원소 개수, 자료형 등을 확인하는 예제입니다.
print('a.shape =', a.shape)
print('len(a) =', len(a))
print('b.ndim =', b.ndim)
print('e.size =', e.size)
print('b.dtype =', b.dtype)
print('b.dtype.name =', b.dtype.name)
print('b.astype(int) =\n', b.astype(int))

a.shape = (3,)
len(a) = 3
b.ndim = 2
e.size = 4
b.dtype = float64
b.dtype.name = float64
b.astype(int) =
 [[1 2 3]
 [4 5 6]]


### 실행 결과 예시

- `a.shape`는 `(3,)`로 출력되어 1차원 배열 길이가 3임을 보여 줍니다.  
- `b.ndim`은 2이므로 `b`는 2차원 배열입니다.  
- `e.size`는 전체 원소 개수이므로 4가 됩니다.  
- `b.astype(int)`는 실수를 정수로 바꾼 새 배열을 반환합니다.

## 4. 배열 수학 연산

NumPy의 가장 강력한 장점 중 하나는 **반복문 없이 배열 전체에 연산을 적용**할 수 있다는 점입니다.  
치트시트에는 덧셈, 뺄셈, 곱셈, 나눗셈뿐 아니라 지수, 제곱근, 삼각함수, 로그, 내적도 포함되어 있습니다.

In [16]:
# 배열 간 사칙연산과 지수, 제곱근, 삼각함수, 로그, 내적을 계산하는 예제입니다.
print(a)
print(b)
print('a - b =\n', a - b)
print('np.subtract(a, b) =\n', np.subtract(a, b))
print('b + a =\n', b + a)
print('np.add(b, a) =\n', np.add(b, a))
print('a / b =\n', a / b)
print('np.divide(a, b) =\n', np.divide(a, b))
print('a * b =\n', a * b)
print('np.multiply(a, b) =\n', np.multiply(a, b))

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
a - b =
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
np.subtract(a, b) =
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
b + a =
 [[2.5 4.  6. ]
 [5.  7.  9. ]]
np.add(b, a) =
 [[2.5 4.  6. ]
 [5.  7.  9. ]]
a / b =
 [[0.6667 1.     1.    ]
 [0.25   0.4    0.5   ]]
np.divide(a, b) =
 [[0.6667 1.     1.    ]
 [0.25   0.4    0.5   ]]
a * b =
 [[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
np.multiply(a, b) =
 [[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


In [18]:
print('np.exp(b) =\n', np.exp(b))
print('np.sqrt(b) =\n', np.sqrt(b))
print('np.sin(a) =', np.sin(a))
print('np.cos(b) =\n', np.cos(b))
print('np.log(a) =', np.log(a))

np.exp(b) =
 [[  4.4817   7.3891  20.0855]
 [ 54.5982 148.4132 403.4288]]
np.sqrt(b) =
 [[1.2247 1.4142 1.7321]
 [2.     2.2361 2.4495]]
np.sin(a) = [0.8415 0.9093 0.1411]
np.cos(b) =
 [[ 0.0707 -0.4161 -0.99  ]
 [-0.6536  0.2837  0.9602]]
np.log(a) = [0.     0.6931 1.0986]


In [19]:
print(f)
print('e.dot(f) =\n', e.dot(f))

[[1. 0.]
 [0. 1.]]
e.dot(f) =
 [[7. 7.]
 [7. 7.]]


### 실행 결과 예시

- `a - b`, `b + a`처럼 차원이 달라도 브로드캐스팅 규칙이 맞으면 원소별 연산이 가능합니다.  
- `np.exp(b)`는 각 원소에 지수 함수를 적용합니다.  
- `np.sqrt(b)`는 제곱근, `np.sin(a)`는 사인값, `np.log(a)`는 자연로그를 계산합니다.  
- `e.dot(f)`는 행렬 곱셈 성격의 연산이며, 여기서는 `f`가 단위행렬이므로 `e`와 같은 결과가 나옵니다. [file:1]

## 5. 집계 함수

집계 함수는 배열 전체나 특정 축(axis)을 기준으로 요약 통계를 계산할 때 사용합니다.  
합계, 최솟값, 최댓값, 누적합, 평균, 중앙값, 상관계수, 표준편차는 데이터 분석에서 매우 자주 등장합니다. [file:1]

In [20]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [21]:
# 합계, 최솟값, 최댓값, 누적합, 평균, 중앙값, 상관계수, 표준편차를 계산합니다.
print('a.sum() =', a.sum())
print('a.min() =', a.min())
print('b.max(axis=0) =', b.max(axis=0))
print('b.cumsum(axis=1) =\n', b.cumsum(axis=1))
print('a.mean() =', a.mean())
print('np.median(b) =', np.median(b))
print('np.corrcoef(a) =\n', np.corrcoef(a))
print('np.std(b) =', np.std(b))

a.sum() = 6
a.min() = 1
b.max(axis=0) = [4. 5. 6.]
b.cumsum(axis=1) =
 [[ 1.5  3.5  6.5]
 [ 4.   9.  15. ]]
a.mean() = 2.0
np.median(b) = 3.5
np.corrcoef(a) =
 1.0
np.std(b) = 1.5920810978785667


### 실행 결과 예시

- `a.sum()`은 전체 합계인 6을 반환합니다.  
- `b.max(axis=0)`는 열(column) 기준 최댓값을 구합니다.  
- `b.cumsum(axis=1)`는 각 행에서 왼쪽부터 누적합을 계산합니다.  
- `np.median(b)`는 중앙값, `np.std(b)`는 표준편차를 구합니다.  
- `np.corrcoef(a)`는 자기 자신과의 상관을 계산하므로 1에 가까운 값이 나옵니다.

## 6. 비교 연산

NumPy는 비교 결과도 배열로 반환합니다.  
즉, `a == b` 또는 `a < 2` 같은 연산을 하면 각 원소별로 True/False를 담은 불리언 배열이 만들어집니다. [file:1]

In [23]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [25]:
# 배열끼리 또는 배열과 스칼라 값을 비교하는 예제입니다.
print('a == b =\n', a == b)
print('a < 2 =', a < 2)
print('np.array_equal(a, b) =', np.array_equal(a, b))

a == b =
 [[False  True  True]
 [False False False]]
a < 2 = [ True False False]
np.array_equal(a, b) = False


### 실행 결과 예시

- `a == b`는 원소 단위 비교이므로 True/False가 배열로 나옵니다.  
- `a < 2`는 `[ True False False ]` 비슷한 형태가 됩니다.  
- `np.array_equal(a, b)`는 배열 전체가 완전히 같은지 한 번에 판단합니다. [file:1]

## 7. 복사와 뷰

NumPy에서 매우 중요한 개념이 **view**와 **copy**입니다.  
view는 원본 데이터를 함께 바라보는 얕은 참조이고, copy는 별도의 메모리에 독립적으로 복사한 객체입니다. [file:1]

In [26]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [27]:
# view와 copy의 차이를 보여 주기 위한 배열 복사 예제입니다.
h_view = a.view()
h_copy_func = np.copy(a)
h_copy_method = a.copy()

print('view =', h_view)
print('np.copy(a) =', h_copy_func)
print('a.copy() =', h_copy_method)

view = [1 2 3]
np.copy(a) = [1 2 3]
a.copy() = [1 2 3]


In [28]:
h_view[0] = 100
h_view, a

(array([100,   2,   3]), array([100,   2,   3]))

In [29]:
h_copy_func[0] = 1000
h_copy_func, a

(array([1000,    2,    3]), array([100,   2,   3]))

In [30]:
h_copy_method[0] = 2000
h_copy_method, a

(array([2000,    2,    3]), array([100,   2,   3]))

### 실행 결과 예시

출력만 보면 세 결과가 비슷해 보일 수 있습니다.  
하지만 이후 원본 배열 `a`를 바꾸면 `view`는 영향을 받을 수 있고, `copy`는 독립적으로 유지됩니다.  
실무에서는 원본 보존 여부가 중요하므로 이 차이를 꼭 이해해야 합니다.

## 8. 정렬

치트시트에는 `a.sort()`와 `c.sort(axis=0)` 예제가 나옵니다.  
정렬은 축(axis)을 기준으로 동작하므로, 어떤 방향으로 정렬되는지 이해하는 것이 중요합니다.

In [120]:
# 1차원, 2차원, 3차원 NumPy 배열을 생성하는 예제입니다.
a = np.array([3, 2, 1])
print('a =\n', a)
# 1차원 배열과 다차원 배열을 정렬하는 예제입니다.
a_sorted = a.copy()
a_sorted.sort()
print('a.sort() ->', a_sorted)

a =
 [3 2 1]
a.sort() -> [1 2 3]


In [121]:
c = np.array(np.arange(12, 0, -1)).reshape(2, 2, 3)
print('c =\n', c, "\n")
c_sorted = c.copy()
c_sorted.sort(axis=0) #  모든 원소에서 슬라이스끼리 정렬
c_sorted

c =
 [[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]] 



array([[[ 6,  5,  4],
        [ 3,  2,  1]],

       [[12, 11, 10],
        [ 9,  8,  7]]])

In [122]:
c = np.array(np.arange(12, 0, -1)).reshape(2, 2, 3)
print('c =\n', c, "\n")
c_sorted = c.copy()
c_sorted.sort(axis=1) # 슬라이스 내에서 행끼리 정렬
c_sorted

c =
 [[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]] 



array([[[ 9,  8,  7],
        [12, 11, 10]],

       [[ 3,  2,  1],
        [ 6,  5,  4]]])

In [123]:
c = np.array(np.arange(12, 0, -1)).reshape(2, 2, 3)
print('c =\n', c, "\n")
c_sorted = c.copy()
c_sorted.sort(axis=2) # 행 내에서 열끼리 정렬
c_sorted

c =
 [[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]] 



array([[[10, 11, 12],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [ 1,  2,  3]]])

### axis=0 — 슬라이스 방향 정렬
- 고정: [j, k] (행·열 위치) → 비교: c[0][j,k] vs c[1][j,k]
- 각 [j,k] 위치에서 슬라이스끼리 값을 비교해 오름차순 재배치합니다. 결과적으로 sorted[0]에 각 위치의 min이, sorted[1]에 max가 모입니다. 이 예제에서는 c[0]의 모든 값(7~12)이 c1보다 크므로 슬라이스 전체가 뒤집힌 것처럼 보이지만, 알고리즘은 어디까지나 element-wise입니다.

### axis=1 — 행 방향 정렬
- 고정: [i, k] (슬라이스·열 위치) → 비교: c[i][0,k] vs c[i][1,k]
- 각 슬라이스 내부에서, 열 위치를 고정하고 행들 사이 값을 비교합니다. 슬라이스 간 교환은 전혀 없고, 슬라이스 0과 슬라이스 1이 각각 독립적으로 정렬됩니다.

### axis=2 — 열 방향 정렬
- 고정: [i, j] (슬라이스·행 위치) → 비교: 해당 행의 원소들 c[i,j,0..2]
- 가장 직관적인 케이스입니다. 각 행을 독립적으로 오름차순 정렬하고, 슬라이스 구조와 행 구조는 그대로 유지됩니다. 2D 배열에서 axis=1로 정렬하는 것과 완전히 동일한 개념이 각 슬라이스에 반복 적용되는 것입니다.

### 실행 결과 예시

- 1차원 배열은 작은 값부터 큰 값 순으로 정렬됩니다.  
- 다차원 배열은 `axis=0`이면 첫 번째 축을 따라 각 위치별로 정렬됩니다.  
정렬은 데이터 전처리나 순위 계산 전에 자주 사용됩니다.

In [124]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]], dtype=float)
print('c =\n', c,  "\n")

c_sorted = c.copy()
c_sorted.sort(axis=0)
print('c.sorted(axis=0) =\n', c_sorted)

c =
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] 

c.sorted(axis=0) =
 [[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


## 9. 부분집합, 슬라이싱, 인덱싱

NumPy 배열도 파이썬 리스트처럼 인덱싱과 슬라이싱이 가능합니다.  
다만 2차원 이상에서는 행과 열을 동시에 선택할 수 있기 때문에 훨씬 강력합니다. [file:1]

In [56]:
# 1차원, 2차원, 3차원 NumPy 배열을 생성하는 예제입니다.
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
c = np.array([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]], dtype=float)

print('a =\n', a)
print('b =\n', b)
print('c =\n', c)

a =
 [1 2 3]
b =
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
c =
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [58]:
# 특정 원소 선택, 구간 슬라이싱, 행/열 선택, 역순 조회를 보여 줍니다.
print('a[2] =', a[2])
print('b[1,2] =', b[1, 2], b[1][2])
print('a[0:2] =', a[0:2])
print('b[0:2,1] =', b[0:2, 1])
print('b[:1] =\n', b[:1])
print('c[1,...] =\n', c[1, ...])
print('a[::-1] =', a[::-1])

a[2] = 3
b[1,2] = 6.0 6.0
a[0:2] = [1 2]
b[0:2,1] = [2. 5.]
b[:1] =
 [[1.5 2.  3. ]]
c[1,...] =
 [[3. 2. 1.]
 [4. 5. 6.]]
a[::-1] = [3 2 1]


### 실행 결과 예시

- `a[2]`는 세 번째 원소인 3을 선택합니다.  
- `b[1,2]`는 2행 3열 위치의 값인 6.0을 선택합니다.  
- `a[0:2]`는 처음 두 원소를 가져옵니다.  
- `a[::-1]`는 배열을 역순으로 뒤집습니다.  
- `c[1,...]`에서 `...`는 나머지 모든 축을 의미합니다.

## 10. 불리언 인덱싱과 팬시 인덱싱

인덱싱은 NumPy의 핵심 활용 포인트입니다.  
조건으로 원소를 고르는 불리언 인덱싱과, 원하는 위치를 직접 지정하는 팬시 인덱싱을 익히면 데이터 추출이 훨씬 쉬워집니다.

In [59]:
print('a =\n', a)
print('b =\n', b)

a =
 [1 2 3]
b =
 [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
# 조건에 맞는 원소를 선택하는 불리언 인덱싱과 위치 기반 팬시 인덱싱 예제입니다.
print('a[a < 2] =', a[a < 2])
print('b[[1,0,1,0],[0,1,2,0]] =', b[[1,0,1,0],[0,1,2,0]])
print('b[[1,0,1,0]][:,[0,1,2,0]] =\n', b[[1,0,1,0]][:,[0,1,2,0]])

a[a < 2] = [1]
b[[1,0,1,0],[0,1,2,0]] = [4.  2.  6.  1.5]
b[[1,0,1,0]][:,[0,1,2,0]] =
 [[4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]
 [4.  5.  6.  4. ]
 [1.5 2.  3.  1.5]]


In [60]:
b[[1,0,1,0]]

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1.5, 2. , 3. ]])

In [62]:
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

### 실행 결과 예시

- `a[a < 2]`는 조건을 만족하는 값만 남겨 `[1]`이 됩니다.  
- `b[[1,0,1,0],[0,1,2,0]]`는 지정한 좌표의 값을 한 번에 가져옵니다.  
- 두 번째 예제는 먼저 행을 고른 뒤, 다시 열을 선택해 부분행렬을 만드는 방식입니다.

## 11. 배열 형태 변경

데이터를 분석하다 보면 같은 데이터라도 모양(shape)을 바꿔야 할 때가 많습니다.  
전치, 평탄화, reshape는 데이터를 재배열하는 대표적인 연산입니다.

In [63]:
a, b

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]))

In [71]:
# 전치(transpose), 평탄화(ravel), 모양 변경(reshape)을 수행합니다.
i = np.transpose(b)
print('np.transpose(b) =\n', i)
print('i.T =\n', i.T)
print('b.ravel() =', b.ravel())

np.transpose(b) =
 [[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
i.T =
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
b.ravel() = [1.5 2.  3.  4.  5.  6. ]


In [69]:
g = a - b
print(g)
print('g.reshape(3, -2) =\n', g.reshape(3, -2))

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
g.reshape(3, -2) =
 [[-0.5  0. ]
 [ 0.  -3. ]
 [-3.  -3. ]]


### 실행 결과 예시

- `np.transpose(b)`는 행과 열을 뒤바꿉니다.  
- `i.T`도 전치와 같은 의미입니다.  
- `b.ravel()`은 다차원 배열을 1차원으로 펼칩니다.  
- `reshape(3, -2)`는 한쪽 크기를 자동 계산해 새로운 shape으로 바꿉니다.  
실무에서는 머신러닝 입력 형태를 맞출 때 자주 사용합니다.

## 12. 요소 추가와 삭제

배열의 모양을 바꾸거나 원소를 추가, 삽입, 삭제하는 기능도 치트시트에 포함되어 있습니다.  
다만 NumPy 배열은 리스트처럼 가변 길이 구조가 아니므로, 내부적으로는 새 배열이 만들어지는 경우가 많습니다.

In [78]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [79]:
# 배열 크기 변경과 원소 추가/삽입/삭제를 수행하는 예제입니다.
h = np.array([1, 2, 3, 4, 5, 6])
h.resize((2, 3))
print('resized h =\n', h)
print('np.append(h, g) =', np.append(h, g))

resized h =
 [[1 2 3]
 [4 5 6]]
np.append(h, g) = [ 1.   2.   3.   4.   5.   6.  -0.5  0.   0.  -3.  -3.  -3. ]


In [73]:
print(a)
print('np.insert(a, 1, 5) =', np.insert(a, 1, 5))
print('np.delete(a, [1]) =', np.delete(a, [1]))

[1 2 3]
np.insert(a, 1, 5) = [1 5 2 3]
np.delete(a, [1]) = [1 3]


In [83]:
k = np.arange(10).reshape(2, 5)
print(k)
p = np.append(k, np.arange(5))
print(p)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4]


### 실행 결과 예시

- `resize((2,3))`는 배열 shape을 2행 3열로 바꿉니다.  
- `np.append`는 배열을 1차원으로 바꾸어 추가합니다.  
- `np.insert(a, 1, 5)`는 인덱스 1 위치에 5를 삽입합니다.  
- `np.delete(a, [1])`는 두 번째 원소를 삭제한 새 배열을 만듭니다.

## 13. 배열 결합

여러 배열을 하나로 합치는 작업도 매우 중요합니다.  
행 방향 결합, 열 방향 결합, 단순 이어 붙이기 등은 데이터 병합의 기초입니다.

In [86]:
print(a)
print(b)
print(d)
print(e)
print(f)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[10 15 20]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [ ]:
# 여러 배열을 세로, 가로, 열 방향으로 결합하는 방법을 보여 줍니다.
print('np.concatenate((a, d), axis=0) =', np.concatenate((a, d), axis=0))
print('np.vstack((a, b)) =\n', np.vstack((a, b)))
print('np.r_[e, f] =\n', np.r_[e, f])
print('np.hstack((e, f)) =\n', np.hstack((e, f)))
print('np.column_stack((a, d)) =\n', np.column_stack((a, d)))
print('np.c_[a, d] =\n', np.c_[a, d])

np.concatenate((a, d), axis=0) = [ 1  2  3 10 15 20]
np.vstack((a, b)) =
 [[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]
np.r_[e, f] =
 [[7. 7.]
 [7. 7.]
 [1. 0.]
 [0. 1.]]
np.hstack((e, f)) =
 [[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
np.column_stack((a, d)) =
 [[ 1 10]
 [ 2 15]
 [ 3 20]]
np.c_[a, d] =
 [[ 1 10]
 [ 2 15]
 [ 3 20]]


### 실행 결과 예시

- `np.concatenate((a, d), axis=0)`는 1차원 배열 두 개를 이어 붙입니다.  
- `np.vstack((a, b))`는 위아래로 쌓아 2차원 배열을 만듭니다.  
- `np.hstack((e, f))`는 좌우로 붙입니다.  
- `np.column_stack((a, d))`와 `np.c_[a, d]`는 열 기준으로 묶어 2열짜리 배열을 만듭니다.

## 14. 배열 분할

배열 결합의 반대 작업이 분할입니다.  
큰 배열을 여러 조각으로 나누어 처리할 때 사용합니다.

In [87]:
a

array([1, 2, 3])

In [88]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [90]:
# 배열을 가로와 세로 방향으로 분할하는 예제입니다.
print('np.hsplit(a, 3) =\n', np.hsplit(a, 3))
print('np.vsplit(c, 2) =\n', np.vsplit(c, 2))

np.hsplit(a, 3) =
 [array([1]), array([2]), array([3])]
np.vsplit(c, 2) =
 [array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
        [4., 5., 6.]]])]


### 실행 결과 예시

- `np.hsplit(a, 3)`는 1차원 배열을 3개 조각으로 나눕니다.  
- `np.vsplit(c, 2)`는 첫 번째 축 기준으로 나누어 3차원 배열을 둘로 쪼갭니다.  
이런 기능은 데이터 배치(batch)를 나누거나, 훈련/검증 데이터를 분리할 때 응용할 수 있습니다.

## 16. 대표 데이터 타입

치트시트 마지막 부분에는 NumPy의 주요 자료형이 소개됩니다.  
정수형, 실수형, 복소수형, 불리언형, 문자열형 등은 메모리 사용량과 계산 정확도에 직접 영향을 줍니다. [file:1]

In [93]:
# NumPy에서 자주 보는 대표 자료형 객체를 확인합니다.
print('대표 데이터 타입 예시')
print(np.int64)
print(np.float32)
print(np.complex128)
print(np.bool_)
print(np.object_)
print(np.bytes_)
print(np.str_)

대표 데이터 타입 예시
<class 'numpy.int64'>
<class 'numpy.float32'>
<class 'numpy.complex128'>
<class 'numpy.bool'>
<class 'numpy.object_'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>


### 실행 결과 예시

각 줄에는 NumPy의 자료형 객체 이름이 출력됩니다.  
예를 들어 `np.int64`는 64비트 정수형, `np.float32`는 32비트 실수형을 뜻합니다.  
데이터 크기와 정밀도 사이의 균형을 잡는 데 매우 중요한 개념입니다.

## 17. 치트시트와 실제 사용법의 차이

치트시트는 빠르게 훑어보기 좋은 자료이지만, 실제 코드에서는 약간 다르게 쓰는 부분도 있습니다.  
예를 들어 치트시트에는 `b.median()` 또는 `a.corrcoef()`처럼 보이는 표기가 있지만, 일반적인 NumPy 사용에서는 `np.median(b)`, `np.corrcoef(a)`처럼 함수 형태가 더 자연스럽습니다.

## 18. 복습 포인트

이 노트북에서 꼭 기억해야 할 핵심은 다음과 같습니다.

- NumPy는 다차원 배열을 빠르게 처리하는 핵심 라이브러리입니다.
- 배열 생성 함수(`zeros`, `ones`, `arange`, `linspace`)는 매우 자주 사용됩니다.
- 수학 연산과 집계 함수는 배열 전체에 벡터화되어 적용됩니다.
- 인덱싱, 슬라이싱, reshape, concatenate는 데이터 가공의 기본기입니다.
- `.npy`, `.npz` 파일 저장/불러오기는 실무에서 유용합니다.